package com.geobudget.geobudget.service;

import com.geobudget.geobudget.dto.CurrencyDto;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class CurrencyService {

    public List<CurrencyDto> getCurrencies() {
        return List.of(
            CurrencyDto.builder().code("RUB").name("Российский рубль").symbol("₽").build(),
            CurrencyDto.builder().code("USD").name("Доллар США").symbol("$").build(),
            CurrencyDto.builder().code("EUR").name("Евро").symbol("€").build(),
            CurrencyDto.builder().code("GBP").name("Британский фунт").symbol("£").build(),
            CurrencyDto.builder().code("JPY").name("Японская иена").symbol("¥").build(),
            CurrencyDto.builder().code("CHF").name("Швейцарский франк").symbol("Fr").build(),
            CurrencyDto.builder().code("CNY").name("Китайский юань").symbol("¥").build(),
            CurrencyDto.builder().code("INR").name("Индийская рупия").symbol("₹").build(),
            CurrencyDto.builder().code("BRL").name("Бразильский реал").symbol("R$").build(),
            CurrencyDto.builder().code("KRW").name("Южнокорейская вона").symbol("₩").build(),
            CurrencyDto.builder().code("TRY").name("Турецкая лира").symbol("₺").build(),
            CurrencyDto.builder().code("PLN").name("Польский злотый").symbol("zł").build(),
            CurrencyDto.builder().code("UAH").name("Украинская гривна").symbol("₴").build(),
            CurrencyDto.builder().code("KZT").name("Казахстанский тенге").symbol("₸").build(),
            CurrencyDto.builder().code("BYN").name("Белорусский рубль").symbol("Br").build(),
            CurrencyDto.builder().code("CAD").name("Канадский доллар").symbol("C$").build(),
            CurrencyDto.builder().code("AUD").name("Австралийский доллар").symbol("A$").build(),
            CurrencyDto.builder().code("NZD").name("Новозеландский доллар").symbol("NZ$").build(),
            CurrencyDto.builder().code("SEK").name("Шведская крона").symbol("kr").build(),
            CurrencyDto.builder().code("NOK").name("Норвежская крона").symbol("kr").build(),
            CurrencyDto.builder().code("DKK").name("Датская крона").symbol("kr").build(),
            CurrencyDto.builder().code("CZK").name("Чешская крона").symbol("Kč").build(),
            CurrencyDto.builder().code("HUF").name("Венгерский форинт").symbol("Ft").build(),
            CurrencyDto.builder().code("RON").name("Румынский лей").symbol("lei").build(),
            CurrencyDto.builder().code("BGN").name("Болгарский лев").symbol("лв").build(),
            CurrencyDto.builder().code("HRK").name("Хорватская куна").symbol("kn").build(),
            CurrencyDto.builder().code("RSD").name("Сербский динар").symbol("дин").build(),
            CurrencyDto.builder().code("MKD").name("Македонский денар").symbol("ден").build(),
            CurrencyDto.builder().code("RON").name("Молдавский лей").symbol("L").build(),
            CurrencyDto.builder().code("GEL").name("Грузинский лари").symbol("₾").build(),
            CurrencyDto.builder().code("AMD").name("Армянский драм").symbol("֏").build(),
            CurrencyDto.builder().code("AZN").name("Азербайджанский манат").symbol("₼").build(),
            CurrencyDto.builder().code("UZS").name("Узбекский сум").symbol("сўм").build(),
            CurrencyDto.builder().code("TJS").name("Таджикский сомони").symbol("ЅМ").build(),
            CurrencyDto.builder().code("TMT").name("Туркменский манат").symbol("m").build(),
            CurrencyDto.builder().code("KGS").name("Киргизский сом").symbol("сом").build(),
            CurrencyDto.builder().code("MNT").name("Монгольский тугрик").symbol("₮").build(),
            CurrencyDto.builder().code("VND").name("Вьетнамский донг").symbol("₫").build(),
            CurrencyDto.builder().code("THB").name("Тайский бат").symbol("฿").build(),
            CurrencyDto.builder().code("MYR").name("Малайзийский ринггит").symbol("RM").build(),
            CurrencyDto.builder().code("SGD").name("Сингапурский доллар").symbol("S$").build(),
            CurrencyDto.builder().code("IDR").name("Индонезийская рупия").symbol("Rp").build(),
            CurrencyDto.builder().code("PHP").name("Филиппинское песо").symbol("₱").build(),
            CurrencyDto.builder().code("HKD").name("Гонконгский доллар").symbol("HK$").build(),
            CurrencyDto.builder().code("TWD").name("Тайваньский доллар").symbol("NT$").build(),
            CurrencyDto.builder().code("ZAR").name("Южноафриканский рэнд").symbol("R").build(),
            CurrencyDto.builder().code("EGP").name("Египетский фунт").symbol("E£").build(),
            CurrencyDto.builder().code("MAD").name("Марокканский дирхам").symbol("د.م.").build(),
            CurrencyDto.builder().code("AED").name("Дирхам ОАЭ").symbol("د.إ").build(),
            CurrencyDto.builder().code("SAR").name("Саудовский риал").symbol("﷼").build(),
            CurrencyDto.builder().code("ILS").name("Израильский шекель").symbol("₪").build(),
            CurrencyDto.builder().code("JOD").name("Иорданский динар").symbol("د.ا").build(),
            CurrencyDto.builder().code("LBP").name("Ливанский фунт").symbol("ل.ل").build(),
            CurrencyDto.builder().code("QAR").name("Катарский риал").symbol("ر.ق").build(),
            CurrencyDto.builder().code("KWD").name("Кувейтский динар").symbol("د.ك").build(),
            CurrencyDto.builder().code("BHD").name("Бахрейнский динар").symbol(".د.ب").build(),
            CurrencyDto.builder().code("OMR").name("Оманский риал").symbol("ر.ع.").build(),
            CurrencyDto.builder().code("PKR").name("Пакистанская рупия").symbol("₨").build(),
            CurrencyDto.builder().code("BDT").name("Бангладешская така").symbol("৳").build(),
            CurrencyDto.builder().code("LKR").name("Шри-ланкийская рупия").symbol("Rs").build(),
            CurrencyDto.builder().code("NPR").name("Непальская рупия").symbol("रू").build(),
            CurrencyDto.builder().code("MMK").name("Мьянманский кьят").symbol("K").build(),
            CurrencyDto.builder().code("KHR").name("Камбоджийский риель").symbol("៛").build(),
            CurrencyDto.builder().code("LAK").name("Лаосский кип").symbol("₭").build(),
            CurrencyDto.builder().code("MXN").name("Мексиканское песо").symbol("Mex$").build(),
            CurrencyDto.builder().code("ARS").name("Аргентинское песо").symbol("$").build(),
            CurrencyDto.builder().code("CLP").name("Чилийское песо").symbol("$").build(),
            CurrencyDto.builder().code("COP").name("Колумбийское песо").symbol("$").build(),
            CurrencyDto.builder().code("PEN").name("Перуанский соль").symbol("S/").build(),
            CurrencyDto.builder().code("UYU").name("Уругвайское песо").symbol("$U").build(),
            CurrencyDto.builder().code("PYG").name("Парагвайский гуарани").symbol("₲").build(),
            CurrencyDto.builder().code("BOB").name("Боливийский боливиано").symbol("Bs").build(),
            CurrencyDto.builder().code("VES").name("Венесуэльский боливар").symbol("Bs.S").build(),
            CurrencyDto.builder().code("CRC").name("Костариканский колон").symbol("₡").build(),
            CurrencyDto.builder().code("PAB").name("Панамская бальбоа").symbol("B/").build(),
            CurrencyDto.builder().code("DOP").name("Доминиканское песо").symbol("RD$").build(),
            CurrencyDto.builder().code("GTQ").name("Гватемальский кетсаль").symbol("Q").build(),
            CurrencyDto.builder().code("HNL").name("Гондурасская лемпира").symbol("L").build(),
            CurrencyDto.builder().code("NIO").name("Никарагуанская кордоба").symbol("C$").build(),
            CurrencyDto.builder().code("SVC").name("Сальвадорский колон").symbol("₡").build(),
            CurrencyDto.builder().code("CUP").name("Кубинское песо").symbol("₱").build(),
            CurrencyDto.builder().code("JMD").name("Ямайский доллар").symbol("J$").build(),
            CurrencyDto.builder().code("TTD").name("Доллар Тринидада и Тобаго").symbol("TT$").build(),
            CurrencyDto.builder().code("BBD").name("Барбадосский доллар").symbol("Bds$").build(),
            CurrencyDto.builder().code("BSD").name("Багамский доллар").symbol("B$").build(),
            CurrencyDto.builder().code("BZD").name("Белизский доллар").symbol("BZ$").build(),
            CurrencyDto.builder().code("GYD").name("Гаянский доллар").symbol("G$").build(),
            CurrencyDto.builder().code("SRD").name("Суринамский доллар").symbol("Sr$").build(),
            CurrencyDto.builder().code("XAF").name("Центральноафриканский франк").symbol("Fr").build(),
            CurrencyDto.builder().code("XOF").name("Западноафриканский франк").symbol("Fr").build(),
            CurrencyDto.builder().code("XCD").name("Восточно-карибский доллар").symbol("EC$").build(),
            CurrencyDto.builder().code("NGN").name("Нигерийская найра").symbol("₦").build(),
            CurrencyDto.builder().code("GHS").name("Ганский седи").symbol("₵").build(),
            CurrencyDto.builder().code("KES").name("Кенийский шиллинг").symbol("KSh").build(),
            CurrencyDto.builder().code("UGX").name("Угандский шиллинг").symbol("USh").build(),
            CurrencyDto.builder().code("TZS").name("Танзанийский шиллинг").symbol("TSh").build(),
            CurrencyDto.builder().code("RWF").name("Руандийский франк").symbol("FRw").build(),
            CurrencyDto.builder().code("ETB").name("Эфиопский бирр").symbol("Br").build(),
            CurrencyDto.builder().code("SDG").name("Суданский фунт").symbol("ج.س.").build(),
            CurrencyDto.builder().code("MUR").name("Маврикийская рупия").symbol("₨").build(),
            CurrencyDto.builder().code("SCR").name("Сейшельская рупия").symbol("₨").build(),
            CurrencyDto.builder().code("MZN").name("Мозамбикский метикал").symbol("MT").build(),
            CurrencyDto.builder().code("ZMW").name("Замбийская квача").symbol("ZK").build(),
            CurrencyDto.builder().code("BWP").name("Ботсванская пула").symbol("P").build(),
            CurrencyDto.builder().code("NAD").name("Намибийский доллар").symbol("N$").build(),
            CurrencyDto.builder().code("SZL").name("Эсватиний лилангени").symbol("E").build(),
            CurrencyDto.builder().code("LSL").name("Лесотский лоти").symbol("L").build(),
            CurrencyDto.builder().code("MGA").name("Малагасийский ариари").symbol("Ar").build(),
            CurrencyDto.builder().code("MWK").name("Малавийская квача").symbol("MK").build(),
            CurrencyDto.builder().code("AOA").name("Ангольская кванза").symbol("Kz").build(),
            CurrencyDto.builder().code("CDF").name("Конголезский франк").symbol("FC").build(),
            CurrencyDto.builder().code("ISK").name("Исландская крона").symbol("kr").build(),
            CurrencyDto.builder().code("GIP").name("Гибралтарский фунт").symbol("£").build(),
            CurrencyDto.builder().code("FKP").name("Фунт Фолклендских островов").symbol("£").build(),
            CurrencyDto.builder().code("SHP").name("Фунт Святой Елены").symbol("£").build(),
            CurrencyDto.builder().code("MDL").name("Молдавский лей").symbol("L").build()
        );
    }
}
